import Nav from './auth/Nav'
import './globals.css'
import QueryWrapper from "./auth/QueryWrapper"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className='bg-gray-300'>
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>

      </body>
    </html>
  )
}
